import Head from 'next/head'
import Image from 'next/image'
import React from 'react'
import Header from '../components/Header'
import Logo from '@images/Logo.png'

const Home = () => {
  return (
    <div>
      <Head>
        <title>iFuture</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header>
        <Image alt="image" src={Logo} />
      </Header>
    </div>
  )
}

export default Home
