import Head from 'next/head'
import Image from 'next/image'
import React from 'react'
import Header from '../components/Header'
import Logo from '@images/Logo.png'
import BannerSlogan from '@components/BannerSlogan'
import Input from '@components/Input'
import { FormContainer } from '@styles/pages'
import Footer from '@components/Footer'
import Button from '@components/Button'
import Pill from '@components/Pill'
import Title from '@components/Title'

const Home = () => {
  return (
    <div>
      <Head>
        <title>iFuture</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div style={{ width: '100vw', minWidth: '375px' }}>
        <Header>
          <Image alt="image" src={Logo} />
        </Header>
        <BannerSlogan
          title="Escreva um e-mail para o futuro"
          subTitle="Se você pudesse enviar uma mensagem, igual aquelas capsulas
           do tempo em que você vê em filmes, o que você enviaria?"
        />
        <FormContainer>
          <Input
            label="Digite seu e-mail"
            placeholder="seuemail@email.com"
            name="email"
            register={() => console.log()}
          />
          <Input
            label="Digite o assunto do e-mail"
            placeholder="Assunto..."
            name="assunto"
            register={() => console.log()}
            counter={0}
            maxLength={64}
            errorMessage="error message"
          />
          <Input
            label="Escreva a sua mensagem"
            placeholder="Querido futuro..."
            name="message"
            register={() => console.log()}
            counter={0}
            maxLength={255}
            errorMessage="error message"
          />

          <Title>Gostaria de receber quando?</Title>

          <div style={{ display: 'flex', gap: '16px', flexWrap: 'wrap' }}>
            <Pill>Em 1 ano</Pill>
            <Pill>Em 3 anos</Pill>
            <Pill>Em 5 anos</Pill>
          </div>

          <Button>
            Enviar e-mail para o futuro
            <svg
              width="24"
              height="24"
              viewBox="0 0 24 24"
              fill="none"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                d="M5 12H19"
                stroke="white"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
              <path
                d="M12 5L19 12L12 19"
                stroke="white"
                strokeWidth="2"
                strokeLinecap="round"
                strokeLinejoin="round"
              />
            </svg>
          </Button>
        </FormContainer>
      </div>
      <Footer />
    </div>
  )
}

export default Home
