import Head from 'next/head'
import Image from 'next/image'
import React from 'react'
import Header from '../components/Header'
import Logo from '@images/Logo.png'
import BannerSlogan from '@components/BannerSlogan'

const Home = () => {
  return (
    <div>
      <Head>
        <title>iFuture</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div style={{ width: '100vw', minWidth: '375px' }}>
        <Header>
          <Image alt="image" src={Logo} />
        </Header>
        <BannerSlogan
          title="Escreva um e-mail para o futuro"
          subTitle="Se você pudesse enviar uma mensagem, igual aquelas capsulas
           do tempo em que você vê em filmes, o que você enviaria?"
        />
      </div>
    </div>
  )
}

export default Home
